first try
urfu-2017/markup-task-7 pull request #1
Opened 2017-11-25 14:51 UTC by Morkhod

2017-11-25 14:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-28 22:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-06 07:36 UTC, savichev-igor requested changes
Местами несоответствие цветов в макете и отсутствие `cursor: pointer` на интерактивных элементах

🍅

2017-12-06 07:36 UTC, Savichev-Igor commented on index.css
> +    width: 1416px;
Почему такая точность в задании обеих сторон?

Так можно сломать пропорции картинки и нужно задавать только одну сторону стараться

2017-12-06 11:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-08 08:58 UTC, Savichev-Igor commented
Почему логотип чёрный?)
![image](https://user-images.githubusercontent.com/7279995/33758387-da75d9c8-dc1f-11e7-97f3-510b68772ba1.png)

2017-12-08 13:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-08 13:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-08 14:04 UTC, Savichev-Igor commented
⭐️

2017-12-08 14:04 UTC, savichev-igor approved these changes

2017-12-08 14:04 UTC, closed without merging