uncompleted version
urfu-2017/markup-task-7 pull request #22
Opened 2017-11-27 21:07 UTC by ArtyMgn

2017-11-27 21:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-28 21:01 UTC, f0rmat1k requested changes
Не выполнено:
> Персонажей и ссылки на социальные сети нужно реализовать спрайтами, причем, спрайт с иконками социальных сетей придется превратить в base64

— Встречается шрифт с засечками, которого нет в макетах.
— Персонажи не реагируют на клик, как написано в задаче.

2017-11-28 21:01 UTC, f0rmat1k commented on index.html
> +        <div class="Layer-171">
Откуда такое имя класса? Похоже на копипасту какого-нибудь аля дримвивера. 🤔

2017-11-28 21:01 UTC, f0rmat1k commented on index.html
> +            <div class="textBox1">
еще одно странное имя.

2017-11-28 21:01 UTC, f0rmat1k commented on index.html
> +            <div class="ExampleVideo">
класс с большой буквы.

2017-11-28 21:01 UTC, f0rmat1k commented on index.html
> +                <!--  <div class="personDescription">
не стоит оставлять комменты.

2017-11-28 21:01 UTC, f0rmat1k commented on index.html
> +                <div class="text2 textInblock">
Плохое имя класса. Я так полагаю, ты многое копипастил с цеплина в виде готового кода. Но как результат тебе пришло много странных классов, а такое картинок с srcset, где для всех плотностей указана одна и та же картинка, т.е. они бессмысленны.

2017-11-28 21:08 UTC, ArtyMgn commented on index.html
> +                <div class="text2 textInblock">
из названия коммита вроде понятно, что я еще не довел задачу до финала. Так как проверка предыдущей задачи произошла довольно поздно, приходится тратить время на исправление предыдущего таска. не совсем понятно, что не так с <img alt="cup" class="cupImage" src="img/cup.png"
+                srcset="img/cup.png 2x,
+                        img/cup.png 3x">

2017-11-28 21:10 UTC, f0rmat1k commented on index.html
> +                <div class="text2 textInblock">
@ArtyMgn Ок. Если что, я добавлю сюда тоже несколько дней.

2017-11-29 18:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-30 21:52 UTC, f0rmat1k commented
Пропустил
> белый круг с буквой «Я» с помощью svg.

Но да ладно.

2017-11-30 21:52 UTC, closed without merging