first try
urfu-2017/markup-task-7 pull request #41
Opened 2017-11-28 12:23 UTC by Rolyx2

2017-11-28 12:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-03 15:26 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-05 06:26 UTC, Mokoshka requested changes
Все хорошо, только давай карточки с людьми переверстаем, чтобы не было такого, что контент выходить за границы блока
![2017-12-05 11 24 58](https://user-images.githubusercontent.com/14892550/33592928-f3ffbf26-d9ae-11e7-95d3-971073fd68f0.png)
И чтобы фотография была по центру текста

2017-12-05 08:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-05 09:40 UTC, Mokoshka requested changes
В article вот сколько элементов лежит
![2017-12-05 14-39-10](https://user-images.githubusercontent.com/14892550/33600106-16969102-d9ca-11e7-8315-651bd449c04c.png)
А в итоге 
![2017-12-05 14 39 55](https://user-images.githubusercontent.com/14892550/33600132-2ff4e914-d9ca-11e7-87fc-950f750c3cdf.png)

2017-12-05 10:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-05 11:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-07 12:17 UTC, Mokoshka requested changes

2017-12-07 12:17 UTC, Mokoshka commented on index.css
> +    left: 60px;
Из-за абсолютного позиционирования часть блока выходит из контэйнера
А еще фотография не по центру относительно текста.
Давай в этом случае абсолютно позиционировать только рамку

2017-12-11 10:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-11 11:50 UTC, Mokoshka approved these changes

2017-12-11 11:51 UTC, closed without merging